const jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I used to play piano by ear, but now I use my hands.",
    "What's orange and sounds like a parrot? A carrot!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "used to be a baker, but I couldn't make enough dough.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I used to play piano by ear, but now I use my hands.",
    "What do you call a fish with no eyes? Fsh.",
    "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
    "How do you organize a space party? You 'planet'!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
     "What did one wall say to the other wall? 'I'll meet you at the corner.'",
     "Did you hear about the kidnapping at the playground? They woke up!",
     "I'm reading a book about anti-gravity. It's really uplifting.",
     "Why don't scientists trust atoms? Because they make up everything!",
     "How do you organize a space party? You 'planet'!",
     "What do you call a bear with no teeth? A gummy bear.",
     "What's orange and sounds like a parrot? A carrot.",
     "What do you call a can opener that doesn't work? A can't opener.",
     "Why don't skeletons fight each other? They don't have the guts.",
     "I used to be a baker, but I couldn't make enough dough.",
     "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
     "Did you hear about the claustrophobic astronaut? He just needed a little space.",
     "How do you make a tissue dance? You put a little boogie in it.",
     "What did one plate say to the other plate? 'Lunch is on me!'",
     "Why did the scarecrow win an award? Because he was outstanding in his field!",
     "What do you call a fake noodle? An impasta.",
     "I'm on a whiskey diet. I've lost three days already.",
     "Parallel lines have so much in common. It's a shame they'll never meet.",
     "Why did the math book look sad? Because it had too many problems.",
     "How does a penguin build its house? Igloos it together.",
     "What do you call a cow with no legs? Ground beef.",
     "Did you hear about the guy who invented Lifesavers? He made a mint.",
     "Why did the scarecrow become a successful politician? Because he was outstanding in his field!",
     "I'm friends with all electricians. We have great current connections.",
     "What do you call a bee that can't make up its mind? A maybee.",
     "What's brown and sticky? A stick.",
     "Did you hear about the fire at the circus? It was in tents!",
     "Why don't seagulls fly over the bay? Because then they'd be bagels.",
     "I'm writing a book on reverse psychology. Please don't buy it.",
     "What's green and has wheels? Grass. I lied about the wheels.",
     "Why did the bicycle fall over? Because it was two-tired.",
     "How do you make holy water? You boil the hell out of it.",
     "I used to play piano by ear, but now I use my hands.",
     "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
     "What did one ocean say to the other ocean? Nothing, they just waved.",
     "I'm reading a book on anti-gravity. It's impossible to put down.",
     "Why did the tomato turn red? Because it saw the salad dressing!",
     "What did one wall say to the other wall? 'I'll meet you at the corner.'",
     "Did you hear about the kidnapping at the playground? They woke up!",
     "I'm reading a book about anti-gravity. It's really uplifting.",
     "Why don't scientists trust atoms? Because they make up everything!",
     "How do you organize a space party? You 'planet'!",
     "What do you call a bear with no teeth? A gummy bear.",
     "What's orange and sounds like a parrot? A carrot.",
     "What do you call a can opener that doesn't work? A can't opener.",
     "Why don't skeletons fight each other? They don't have the guts.",
     "I used to be a baker, but I couldn't make enough dough.",
     "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
     "Did you hear about the claustrophobic astronaut? He just needed a little space.",
     "How do you make a tissue dance? You put a little boogie in it.",
     "What did one plate say to the other plate? 'Lunch is on me!'",
     "Why did the scarecrow win an award? Because he was outstanding in his field!",
     "What do you call a fake noodle? An impasta.",
     "I'm on a whiskey diet. I've lost three days already.",
     "Parallel lines have so much in common. It's a shame they'll never meet.",
     "Why did the math book look sad? Because it had too many problems.",
     "How does a penguin build its house? Igloos it together.",
     "What do you call a cow with no legs? Ground beef.",
     "Did you hear about the guy who invented Lifesavers? He made a mint.",
     "Why did the scarecrow become a successful politician? Because he was outstanding in his field!",
     "I'm friends with all electricians. We have great current connections.",
     "What do you call a bee that can't make up its mind? A maybee.",
     "What's brown and sticky? A stick.",
     "Did you hear about the fire at the circus? It was in tents!",
     "Why don't seagulls fly over the bay? Because then they'd be bagels.",
     "I'm writing a book on reverse psychology. Please don't buy it.",
     "What's green and has wheels? Grass. I lied about the wheels.",
     "Why did the bicycle fall over? Because it was two-tired.",
     "How do you make holy water? You boil the hell out of it.",
     "I used to play piano by ear, but now I use my hands.",
     "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
     "What did one ocean say to the other ocean? Nothing, they just waved.",
     "I'm reading a book on anti-gravity. It's impossible to pu      down.",
     "Why did the tomato turn red? Because it saw the salad dressing!",
     "What did one wall say to the other wall? 'I'll meet you at the corner.'",
     "Did you hear about the kidnapping at the playground? They woke up!",
     "I'm reading a book about anti-gravity. It's really uplifting.",
     "Why don't scientists trust atoms? Because they make up everything!",
     "How do you organize a space party? You 'planet'!"
];

const jokes2=[
"क्या आपके पास टाइम है? हां, मेरे पास वॉच है!",
"बच्चा: आप बड़े कैसे हो गए?- माता-पिता ने खाने में दल-रोटी दी थी, और मैंने उसमें बटर डाला!",
"पप्पु: यार, मेरे बच्चों के पास बहुत सारे खेलने के खिलौने हैं।- बन्नू: वाह, कितने बच्चे हैं? - पप्पु: 3, में और मेरे दो दोस्त!",
" टीचर: तुम्हारे पास कितने मित्र हैं?- छात्र: 1000+- टीचर: सच में? वो कैसे?- छात्र: WhatsApp ग्रुप में!",
" बच्चा: आपका नाम क्या है? टीचर: मेरा नाम मिसेस शर्मा है| बच्चा: वाह, आपका शर्मा कैसे आया? ",
" पप्पु: तुम्हारी गर्लफ्रेंड कैसी है? बन्नू: बहुत ही स्मार्ट है, वो तो सिर्फ एक ही बार बोलती है - तू अब बहुत ही अच्छा काम कर रहा है, अगले जनम में मैं तुझसे ही शादी करूंगी।",
" वकील: क्या आपकी पत्नी आपसे खुश है? आदमी: हां, जब वो सोती है तो मुझपर हँसी आ जाती है!",
" बेटा: पापा, आपके पास टैलेंट क्या है? पापा: मेरे पास तो बेटा ही है!",
" पप्पु: मेरी बीवी खुद को बहुत गोरा समझती है।बन्नू: कैसे? पप्पु: हां, जब वो चाय पीती है, तो साथ में समय के साथ दूध भी गोरा हो जाता है!",
" टीचर: तुम्हारे पास तुम्हारे पिता का कोई बड़ा काम नहीं है? छात्र: है, सर. वो हर दिन सुबह मुझे स्कूल छोड़ने आते हैं!",
" बच्चा: डॉक्टर साहब, मेरे पेट में दर्द हो रहा है। डॉक्टर: तुमने कितने साल का नहाने का प्रैक्टिस किया है? बच्चा: अब तक 6 साल से नहाता आ रहा हूँ।- डॉक्टर: तो यही समस्या है, तुम्हें बिना पानी के तो रोज़ नहाना चाहिए!",
" पप्पु: तुमने अपने दोस्त को क्यों मार दिया?- बन्नू: वो मेरे गोलू की मीठाई छिपा रहा था। - पप्पु: तुमने उसे खाने दिया?- बन्नू: नहीं, बल्कि मैंने उसके बगीचे में उसके गोलू को फेंक दिया!",
" आदमी: तुम्हारा बेटा बड़ा हो गया है, क्या वो कोई अच्छा काम कर रहा है?- दोस्त: हां वो अब घर के सारे फाइल्स को डिलीट कर देता है!",
" पप्पु: मेरी बीवी रोज़ मुझसे लड़ती रहती है।- बन्नू: तुम क्या करते हो?- पप्पु: मैं कुछ नहीं करता, बस वो हर बार गलत रुमाल खिच लेती है!",
" वकील: क्या आपके पास तो जबरदस्त बच्चे हैं, सारे उनके ही गुनाहों की तरह दिखते हैं!- माता: जी, क्या आपका बच्चा भी वकील बन गया है?",
" पप्पु: यार, मेरे पास तो एक ख़्वाब है, मैं अमेरिका जाऊं!- बन्नू: तुम्हारे पास विजा है?- पप्पु: नहीं, वाइजा है, मैं तो वाइजा जाऊंगा!",
" टीचर: तुम ने वादा किया था कि तुम कभी झूला नहीं चुराओगे, फिर ये क्या है?- छात्र: मैंने तो झूला नहीं चुराया, मैंने झूले का बर्तन चुराया है!",
" पप्पु: तुम्हारे दोस्त कैसे हैं?- बन्नू: वो तो बहुत ही आलसी हैं, उनका दिन रात से शुरू होता है!",
" वकील: तुमने किसके साथ जगड़ा किया?- मुकदमेदार: बिल्लू के साथ।- वकील: वो कौन है, बिल्लू? - मुकदमेदार: मेरा पड़ोसी का कुत्ता।",
" पप्पु: यार, तुम्हारी बीवी तो बहुत ही ख़ुशमिजाज है।- बन्नू: हां, बस एक ही बात है, वो मेरे साथ ही रहने वाले सबके साथ ख़ुश है!",
"पप्पु: क्या तुम्हारे पास अपना बिज़नेस है? - बन्नू: हां, मेरे पास एक सूट का दुकान है।- पप्पु: वाह, कितनी छोटी दुकान है|- बन्नू: नहीं, दुकान तो बड़ी है, सूट ही छोटा है!",
" बेटा: पापा, मेरे स्कूल के टीचर मेरे पीछे पड़ी हुई हैं! - पापा: अच्छा, वो तुझे गंदी फिल्में देखते हुए पकड़ी हुई होंगी।- बेटा: नहीं, वो मेरे अपने मोबाइल पर मेरे चट्ट की टीचिंग कर रही हैं!",
" टीचर: तुम अपने सबकी कॉपी क्यों देते हो?- छात्र: सर, मैं जिस दिन सबकी कॉपी नहीं देता, वो दिन वो लोग ख़ुद पढ़ते भी नहीं हैं!",
" पप्पु: तुम्हारे पास सब कुछ है, फिर भी तुम हमेशा दुखी रहते हो।- बन्नू: हां, सब कुछ होने के बावजूद एक चीज है जो मेरे पास नहीं है - आपका पैसा !",
" दोस्त: तेरा बेटा कितना तेज़ है!- पप्पु: हां, वो तो रोज़ स्कूल से बग्गा भागकर आता है, बस पिछले हफ्ते तो पुलिस भी भागी हुई थी!",
"पप्पु: मैंने आज तक अपने दोस्त से कभी झूला नहीं मांगा। - बन्नू: क्यों? - पप्पु: क्योंकि उनके पास तो स्विंग है!",
"टीचर: तुम्हारे पिता क्या काम करते हैं?- बच्चा: वो काम करते हैं जिनका कोई और नौकरी नहीं कर सकता!",
"पप्पु: तुम्हारी बीवी तो बहुत खुशमिजाज है!- बन्नू: हां, लेकिन सबसे अच्छी बात यह है कि वो मेरे खुशमिजाज होने पर बराबर हो जाती है!",
"दोस्त: तुम्हारी बीवी कुछ बोलती क्यों नहीं? - पप्पु: अरे, वो तो एक बार बोल देती है, फिर हमें तो सारे वीकेंड बिताने को बोलती है कि बच्चों के साथ बात करें!",
"पप्पु: क्या तुम्हारी बीवी तुमसे प्यार करती है? - बन्नू: हां, वो तो मुझसे प्यार से जलती है!",
"पप्पु: तुम्हारे पास तो बहुत सारे दोस्त हैं, फिर भी तुम अकेले हो क्यों?- बन्नू: हां, वो तो सबके पास दोस्त हैं, मैंने बीवी छोड़ दी!",
"टीचर: तुम्हारे बेटे ने तुम्हारे साथ घर का काम क्यों नहीं करता?- पापा: वो तो सिर्फ़ एक ही वजह से कर लेता है।- टीचर: कौन सी वजह - पापा: जब मैं काम करता हूँ तो उसे स्कूल नहीं जाने देता!",
" बच्चा: टीचर, मुझे ज़ूलॉजी समझ में नहीं आती।- टीचर: क्यों - बच्चा: क्योंकि मेरी बीवी की बातों का भी लॉजिक नहीं समझ में आता!",
" पप्पु: तुम्हारी बीवी तुम पर क्या समझती है?- बन्नू: वो तो मुझे तरसती है कि मैं उसके पास ज्यादा वक़्त बिताऊँ!",
" वकील: तुम्हारे पास कुछ सबूत है कि तुम्हारी पत्नी खूनी है? - पप्पु: हां, मेरे बच्चे के बालों में एक चाकू मिला था!",
];

const jokeText = document.getElementById("joke-text");
const jokeButton = document.getElementById("joke-button");

const jokeText2 = document.getElementById("hin-joke-text");
const jokeButton2 = document.getElementById("hin-joke-button");

jokeButton.addEventListener("click", () => {
    const randomIndex = Math.floor(Math.random() * jokes.length);
    jokeText.textContent = jokes[randomIndex];
});

jokeButton2.addEventListener("click", () => {
    const randomIndex = Math.floor(Math.random() * jokes2.length);
    jokeText2.textContent = jokes2[randomIndex];
});


